[package]
name = "chapter_two"
version = "0.1.0"
authors = ["Richard <r.nguyen.206@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
vec3 = "0.2.1"